# Generated by Django 3.0.5 on 2020-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vg_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='publicado em')),
                ('vg_year', models.IntegerField(verbose_name='ano de lançamento')),
            ],
        ),
    ]
