# Generated by Django 3.0.5 on 2020-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='vg_fab',
            field=models.CharField(default='nome fabricante', max_length=200),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publicado em'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='vg_year',
            field=models.IntegerField(verbose_name='Ano de lançamento'),
        ),
    ]
