# Generated by Django 3.0.5 on 2020-04-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0004_auto_20200424_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publicado em:'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='vg_fab',
            field=models.CharField(default='nome fabricante', max_length=200, verbose_name='Fabricante:'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='vg_name',
            field=models.CharField(max_length=200, verbose_name='Nome do produto:'),
        ),
    ]
